### ISSUE TITLE
Process errors while retrieving latest version

### ISSUE THREAD

**Issue by ilg-ul** [xpack/update-checker-js#16]
In case of errors xpm fails and the stack trace is shown:

```
RequestError: getaddrinfo ENOTFOUND registry.npmjs.org
   at ClientRequest.<anonymous>
(C:\Users\erich\AppData\Roaming\npm\node_modules\xpm\node_modules\got\source
\request-as-event-emitter.js:178:14)
   at Object.onceWrapper (events.js:482:26)
   at ClientRequest.emit (events.js:387:35)
   at ClientRequest.emit (domain.js:470:12)
   at ClientRequest.origin.emit
(C:\Users\erich\AppData\Roaming\npm\node_modules\xpm\node_modules\@szmarczak
\http-timer\source\index.js:37:11)
   at TLSSocket.socketErrorListener (_http_client.js:475:9)
   at TLSSocket.emit (events.js:375:28)
   at TLSSocket.emit (domain.js:470:12)
   at emitErrorNT (internal/streams/destroy.js:106:8)
   at emitErrorCloseNT (internal/streams/destroy.js:74:3)
```

Ignore the error and terminate without error.

**Comment by ilg-ul** [comment]
Fixed on 2021-07-20.
